### ISSUE TITLE
GetWeight & FloorScaleTicket Messages

### ISSUE THREAD

**Issue by kgilliam3662** [ConceptualSystems/sms-mobile-portable#4]
Baldwin Recycling reported that when they are using the new SMSMobile 1.49, that Snapshots images are not showing up.   I've done preliminary research and found that if New Floor Scale Ticket option is chosen and the user fills out all the fields, but clicks CAPTURE to see the 
scale weight, that I see the GETWEIGHT message arrive, i send the weight and snapshot image(s) name back to you, but when the click Transmit, the FLOORSCALETICKET messages arrives with no
snapshot images in either the GrossSnapShotImages or TareSnapShotImages field, causing the Ticket to be saved without the previous Snapshot taken during GETWEIGHT.  If they click Transmit without clicking either Capture button, everything works because SMSMDS takes care of getting the weight and capturing/saving the snapshots.  

[SMSMDS Log for Jarrod.txt](https://github.com/ConceptualSystems/sms-mobile-portable/files/3098899/SMSMDS.Log.for.Jarrod.txt)

**Comment by moonlightcheese** [comment]
The handler for weight capture was being sent a NULL ticket detail value because there is no ticket associated with the floor scale activity when entering values (as there is for the review ticket activity, where we know the ticket and its details returned from MDS).  I inserted a fake ticket detail as the value to send to the weight capture utility which is altered and returned to the floor scale activity.  This was broken during the separation of code for the libraries.  Fixed in SMS Mobile 1.51.

**Comment by kgilliam3662** [comment]
reopen, its still not fixed.  no grossnapshot images are sent back to SMSMDS during Transmit.

I understand that you like to create a single library for all you message, but I believe you need to break this one apart.  Review Ticket has nothing to do with New Floor Scale message.

I need this fixed asap.  My customers are upset, they are losing images that they need now.
